language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

os: linux

cache:
  pip: true

jdk:
  - oraclejdk8

install:
  - pip install -r requirements.txt
  - pip install .
  - mkdir /tmp/elasticsearch
  - wget -O - https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-2.3.3.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1

before_script:
  - /tmp/elasticsearch/bin/elasticsearch -d -D es.path.data=/tmp -D es.path.repo /
  - sleep 10

script:
  - python setup.py test
